name: Deployment Project
on: push
jobs:
  linting:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Run Linting 
        run: npm run lint
  testing:
    needs: [linting]
    runs-on: macos-latest
    steps:
      - name: Run test 
        run: npm run test
  Deployment:
    needs: [testing]
    runs-on: macos-latest
    steps:
      - name: Build Project
        run: npm run build 
      - name: Deploy
        run: echo 'Deploying the project....'
      