name: Matrix Demo
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
  deploy:
    needs: build
    uses: ./.github/workflows/reuse.yml
