name: Reuse Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Artifact name
        default:
        required: false
        type: string
    outputs:
      result:
        value: ${{jobs.build.outputs.outcome}}
jobs:
  build:
    outputs:
      outcome: ${{steps.set-result.outputs.step-result}}
    runs-on: macos-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name}}
      - name: Display files
        run: |
          ls
      - name: Set result outputs
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
