name: Reuse Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Artifact name
        default:
        required: false
        type: string
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Download artifact
        run: actions/download-artifact@v3
        with: ${{inputs.artifact-name}}
      - name: Display files
        run: |
          ls
